apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    name: frontend-pod
    app: guest-book-app
spec:
  containers:
  - name: frontend
    image: kubernetes/guestbook:v2
    ports:
    - name: http
      containerPort: 3000
